# --- Site settings ---
title: Moroccan Association of Polytechnicians in Zurich
description: "Our official website."
theme: minimal-mistakes-jekyll

url: "https://MAPZ-ETH.github.io"
baseurl: ""
permalink: pretty

# --- Logo (Top-level) ---
logo: /assets/images/TATTOO.png

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag